name: http_console
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.4.0 <=3.4.4"

dependencies:
  http: ^1.1.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
